version: 2

project_name: assfonts-go

# before:
#   hooks:
#     - apt-get update
#     - apt-get install -y pkg-config ca-certificates
#     - git clone https://github.com/Microsoft/vcpkg.git /vcpkg
#     - /vcpkg/bootstrap-vcpkg.sh

builds:
  - id: linux-amd64
    main: ./cmd/assfont-go
    binary: assfonts-go
    hooks:
      pre:
        - flock /tmp/vcpkg.lock /vcpkg/vcpkg install --triplet=x64-linux-release --x-install-root=/vcpkg_installed_linux_x64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - PKG_CONFIG_PATH=/vcpkg_installed_linux_x64/x64-linux-release/lib/pkgconfig
    ldflags:
      - -s -w

  - id: windows-amd64
    main: ./cmd/assfont-go
    binary: assfonts-go
    hooks:
      pre:
        - flock /tmp/vcpkg.lock /vcpkg/vcpkg install --triplet=x64-mingw-static --x-install-root=/vcpkg_installed_x64-mingw-static
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - PKG_CONFIG_PATH=/vcpkg_installed_x64-mingw-static/x64-mingw-static/lib/pkgconfig
    ldflags:
      - -s -w

  # - id: darwin-arm64
  #   main: ./cmd/assfont-go
  #   binary: assfonts-go
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #   hooks:
  #     pre:
  #       - flock /tmp/vcpkg.lock /vcpkg/vcpkg install --triplet=arm64-osx-release --x-install-root=/vcpkg_installed_darwin_arm64
  #   env:
  #     - CC=oa64-clang
  #     - CXX=oa64-clang++
  #     - PKG_CONFIG_PATH=/vcpkg_installed_darwin_arm64/arm64-osx-release/lib/pkgconfig
  #   ldflags:
  #     - -s -w

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Akimio521
    name: assfonts-go
  prerelease: auto
  draft: false
